# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  repository_dispatch:
    types:
      - new_recording

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Send data to Python
      run: python pull-data.py -d -u '${{ toJson(github.event.client_payload) }}'
    - name: switching from https to ssh
      run: |
          git config --global user.name 'Matthew Dudak'
          git config --global user.email 'mjdudak@users.noreply.github.com'
    - name: stage changed files
      run: git add .
    - name: check if there is a diff
      run: if [[ "$(git diff --exit-code)" =~ 'diff' ]]; then echo "IS_VALID=true" >> $GITHUB_ENV; else echo "IS_VALID=false" >> $GITHUB_ENV; fi
    - if ${{ env.IS_VALID == 'true' }}
      run: |
        git commit -m 'Auto updated lecture tables'
        git push
